Repository martinaamodt/cockroachdb, pull requests merged in 2019-10, with the labels that each got.

#64 htofix executable
  metadata.json
  tasks/restart_service.sh
Labels: bug

#75 removed puppetlabs-inifile from dependencies
  .fixtures.yml
  metadata.json
Labels: maintenance

#77 Explicitly enable insecure mode
  examples/init.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/cockroachdb_spec.rb
Labels: enhancement

#82 #81
  .travis.yml
Labels: maintenance

#80 Readme
  README.md
Labels: documentation

#83 Fix locality flag
  manifests/init.pp
  manifests/params.pp
  manifests/service.pp
  metadata.json
  templates/cockroachdb.service.epp
Labels: enhancement

#85 Task quit
  tasks/quit.json
  tasks/quit.rb
Labels: enhancement

#87 Added RestartPreventExitStatus to service
  templates/cockroachdb.service.epp
Labels: bug

#88 Secure mode #52
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  manifests/service.pp
  templates/cockroachdb.service.epp
Labels: enhancement

#89 Changed hardcoded names with already existing class params
  manifests/config.pp
  manifests/service.pp
  templates/cockroachdb.service.epp
Labels: bug

#90 Refactor testing - Added new tests to increase coverage
  manifests/params.pp
  spec/classes/cockroachdb_spec.rb
  spec/spec_helper.rb
Labels: maintenance

#91 Puppetstrings
  Gemfile
  REFERENCE.md
  manifests/config.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  manifests/service.pp
Labels: documentation

#92 Choose which fact facter should use to get advertise-address
  manifests/init.pp
  manifests/params.pp
  manifests/service.pp
  templates/cockroachdb.service.epp
Labels: enhancement

#93 v1.0.0
  .travis.yml
  CHANGELOG.md
  Gemfile
  README.md
  REFERENCE.md
  Rakefile
  manifests/config.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  manifests/service.pp
  metadata.json
  spec/classes/cockroachdb_spec.rb
  spec/spec_helper.rb
  tasks/quit.json
  tasks/quit.rb
  templates/cockroachdb.service.epp
Labels: release

#95 Hotfix service template
  CHANGELOG.md
  manifests/service.pp
  metadata.json
  templates/cockroachdb.service.epp
Labels: release

#96 client class to install cockroachdb client
  README.md
  REFERENCE.md
  manifests/client.pp
  spec/classes/client_spec.rb
Labels: enhancement

#97 Fixed param name, install referenced wrong variable name
  REFERENCE.md
  manifests/init.pp
Labels: bug

#98 set service enable equal to true
  manifests/service.pp
  spec/classes/cockroachdb_spec.rb
Labels: bug

#99 Acceptance testing and single node mode
  .fixtures.yml
  .travis.yml
  CONTRIBUTING.md
  Gemfile
  REFERENCE.md
  manifests/init.pp
  manifests/service.pp
  metadata.json
  provision.yaml
  spec/acceptance/client_spec.rb
  spec/acceptance/single_server_spec.rb
  spec/classes/cockroachdb_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
  templates/single_cockroachdb.service.epp
Labels: enhancement

#100 v1.1.0
  .fixtures.yml
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Gemfile
  README.md
  REFERENCE.md
  manifests/client.pp
  manifests/init.pp
  manifests/service.pp
  metadata.json
  provision.yaml
  spec/acceptance/client_spec.rb
  spec/acceptance/single_server_spec.rb
  spec/classes/client_spec.rb
  spec/classes/cockroachdb_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
  templates/single_cockroachdb.service.epp
Labels: release
